[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "http://hylelab.com/*"
  to = "https://hylelab.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.hylelab.com/*"
  to = "https://hylelab.com/:splat"
  status = 301
  force = true 