[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "http://hylelab.com/*"
  to = "https://hylelab.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.hylelab.com/*"
  to = "https://hylelab.com/:splat"
  status = 301
  force = true 